# Generated by Django 5.2.1 on 2025-05-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_name'),
        ('blog', '0003_add_default_categories'),
    ]

    operations = [
    ]
